[package]
name = "st7735-embassy"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal-async = "1.0.0"
embedded-hal = "1.0.0"
embedded-graphics-core = "0.4"
